stages:
  - build
  - deploy

build project:
  stage: build
  image: node:15
  script:
      - npm install --legacy-peer-deps
      - npm run-script build
  artifacts:
    paths:
      - build/

netlify:
  stage: deploy
  image: node:15
  script: 
    - npm install -g netlify-cli
    - netlify deploy --dir=build --prod