stages:
  - test
  - build

test project:
  stage: test
  image: node:14
  script:
      - npm install
      - npm test

build project:
  stage: build
  image: node:14
  script:
      - npm install
      - npm run-script build
