version: '3.9'

services:
  server:
    build: .
    ports: 
      - "8081:8080"
  db:
    image: 'postgres'
    ports:
       - '4444:5432'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'root'
    volumes:
      - ./baza.sql:/docker-entrypoint-initdb.d/init.sql